name: Build
on: [pull_request, push]
jobs:
  pkg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run package

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: cloverleaf
          path: build/cloverleaf-*
