name: Build
on: [pull_request, push]
jobs:
  pkg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run package

      # Uploade each artifact separately
      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: cloverleaf-linux
          path:  build/cloverleaf-linux

      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: cloverleaf-win
          path:  build/cloverleaf-win.exe

      - name: Upload Mac
        uses: actions/upload-artifact@v2
        with:
          name: cloverleaf-mac
          path:  build/cloverleaf-macos
